language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
  - "pypy3"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - stage: codecheck
      python: 3.7
      install:
        - pip install flake8
      script:
        - flake8 sqlparse
      after_success: skip

install:
  - pip install -Uq pytest pytest-cov codecov
  - pytest --version

script:
  - pytest --cov=sqlparse

after_success:
    - codecov
